apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
<<<<<<< Updated upstream
        image: 'us-west1-docker.pkg.dev/qwiklabs-gcp-02-9b145d670d94/my-repository/hello-cloudbuild-dev:v1.0'
=======
        image: 'us-west1-docker.pkg.dev/qwiklabs-gcp-02-9b145d670d94/my-repository/hello-cloudbuild-dev:v2.0'
>>>>>>> Stashed changes
        ports:
        - containerPort: 8080
