apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
<<<<<<< HEAD
        image: 'us-east4-docker.pkg.dev/qwiklabs-gcp-03-397afdf2d18a/my-repository/hello-cloudbuild-dev:v1.0'
=======
        image: 'us-east4-docker.pkg.dev/qwiklabs-gcp-03-868313b20768/my-repository/hello-cloudbuild-dev:v1.0'
>>>>>>> e1e9f6a9b4840461d84428ac698248a5eee36456
        ports:
        - containerPort: 8080
